[tls.options]
  [tls.options.default]
    sniStrict = true
    minVersion = "VersionTLS12"
#    [tls.options.default.clientAuth]
      # in PEM format. each file can contain multiple CAs.
#      caFiles = ["certs/kl_internal_root.pem", "certs/kl_internal_intermediate.pem"]
#      clientAuthType = "NoClientCert"
#      clientAuthType = "RequireAndVerifyClientCert"

#  [tls.options.bypass]
#    sniStrict = true
#    minVersion = "VersionTLS12"
#    [tls.options.bypass.clientAuth]
#      clientAuthType = "NoClientCert"

