FROM arm64v8/debian:bookworm
RUN apt-get update && apt-get install -y bluetooth pulseaudio-module-bluetooth sudo expect alsa-utils curl
RUN curl -sSL https://dtcooper.github.io/raspotify/key.asc | sudo tee /usr/share/keyrings/raspotify_key.asc  > /dev/null \
 && chmod 644 /usr/share/keyrings/raspotify_key.asc \
 && echo 'deb [signed-by=/usr/share/keyrings/raspotify_key.asc] https://dtcooper.github.io/raspotify raspotify main' | sudo tee /etc/apt/sources.list.d/raspotify.list \
 && apt-get update && apt-get install -y raspotify
COPY ./bluezuser.conf /etc/dbus-1/system.d/
RUN useradd -m bluezuser \
 && adduser bluezuser sudo \
 && passwd -d bluezuser
USER bluezuser
ADD file_example_WAV_2MG.wav /
ADD *.sh /
CMD sudo chmod +x *.sh
ENTRYPOINT sh docker_entrypoint.sh